version: '3'

services:
  db:
    image: postgres:latest
    container_name: nextcloud-database
    networks:
      - nextcloud_network
    volumes:
      - ./database:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=pgrandompassword
    restart: unless-stopped

  app:
    image: nextcloud:latest
    container_name: nextcloud-main
    networks:
      - nextcloud_network
    depends_on:
      - db
    ports: 
      - 11111:80
    volumes:
      - ./app:/var/www/html
      - ./app/config:/var/www/html/config
      - ./app/custom_apps:/var/www/html/custom_apps
      - ./app/data:/var/www/html/data
      - ./app/themes:/var/ww/html/themes
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=pgrandompassword
    restart: unless-stopped

networks:
  nextcloud_network: